### ISSUE TITLE
Docker Compose file

### ISSUE THREAD

**Issue by Parlendir** [WeeJeWel/pivpn-web#1]
Hi

Could you please provide an "official" Docker compose file ?

It got to be sth like :

```
version: "2.1"
services:
  pivpn-web:
    image: weejewel/pivpn-web
    container_name: pivpn-web
    environment:
      #- PUID=1000
      #- PGID=1000
      #- TZ=Europe/London
      #- SSH_HOST=<ssh host ip if different>
    volumes:
    #  - /path/to/pivpnweb_config:/config
    ports:
      - 51821:51821
    restart: unless-stopped

```
But it could be easier for everyone if you provide one :)

**Comment by WeeJeWel** [comment]
What's the added benefit actually? I've never used docker compose.

**Comment by Parlendir** [comment]
I's just another way to bring the container online.
I only use docker compose & am not the only one : it's easy to create custom templates (docker-compose) within Portainer.
The docker-compose shows which volumes are to create to have the persistence running and prevents the creation of a randomly named volume by docker, providing an easier way to manage datas on the host.
Moreover, it allows to redeploy easily and quickly the container after an update. (like docker -up you might say :) )

**Comment by WeeJeWel** [comment]
Okay, thanks! If you make it a PR I'd be happy to merge it.

This project doesn't use any volumes or environment variables by default, so you can leave them out.

**Comment by Parlendir** [comment]
Ah ah ^^ I don't know how to do it and dpn't want to be messing around.

But this docker-compose is working

```
version: "2.1"
services:
  pivpn-web:
    image: weejewel/pivpn-web
    container_name: pivpn-web
    environment:
      #- PUID=1000
      #- PGID=1000
      #- TZ=Europe/London
      #- SSH_HOST=<ssh host ip if different>
    ports:
      - 51821:51821
    restart: unless-stopped
```
